// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelDestination.Models;

namespace TravelDestination.Migrations
{
    [DbContext(typeof(TravelDestinationContext))]
    partial class TravelDestinationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TravelDestination.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Country")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Destination")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("ReviewId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ReviewId = 1,
                            City = "Ocean",
                            Country = "Atlantic",
                            Destination = "Bermuda Triangle",
                            Rating = 10
                        },
                        new
                        {
                            ReviewId = 2,
                            City = "Giza",
                            Country = "Egypt",
                            Destination = "Great Pyramids",
                            Rating = 9
                        },
                        new
                        {
                            ReviewId = 3,
                            City = "Beijing",
                            Country = "China",
                            Destination = "Great Wall",
                            Rating = 10
                        },
                        new
                        {
                            ReviewId = 4,
                            City = "Yellowstone",
                            Country = "USA",
                            Destination = "Old Faithful",
                            Rating = 9
                        },
                        new
                        {
                            ReviewId = 5,
                            City = "Portland",
                            Country = "USA",
                            Destination = "Rocky Butte",
                            Rating = 9
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
